import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About metadata",
    description: "Generated by create next app",
}
export default function About() {
    return (
        <h1>about me</h1>
    )
}