import type { Metadata } from "next";

type Props = {
    params: { id: number };
};
export function generateMetadata({
    params,
}: Props): Metadata {
    return {
        title: `Product ${params.id}`,
        description: "Generated by create next app",
    };
}
export default function ProductId({
    params,
}: {
    params: { id: number };
}) {
    return (
        <>
            <h1>Product {params.id}</h1>
        </>
    );
}
