"use client";
import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const links = [
    {
        name: "Navigate to Blog",
        href: "/blog",
    },
    {
        name: "Navigate to Profile",
        href: "/profile",
    },
    {
        name: "Navigate to Product",
        href: "/product",
    },
];

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname();
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}

                {links.map((link,i) => (
                    <Link
                        key={link.href}
                        href={link.href}
                        className={
                            pathname === link.href
                                ? "text-red-600"
                                : ""
                        }
                    >
                        {link.name}
                    </Link>
                ))}
            </body>
        </html>
    );
}
